using FeatureRequestProject.EntityFrameworkCore;
using Xunit;

namespace FeatureRequestProject.EntityFrameworkCore;

public class FeatureRequestProjectEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<FeatureRequestProjectEntityFrameworkCoreFixture>
{

}
